name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore  
    - name: Zip
      uses: papeloto/action-zip@v1
      with:
        files: readme.md src\bin\Release\netcoreapp3.1\*.exe src\bin\Release\netcoreapp3.1\*.dll
        recursive: false
        dest: midisplit.zip
    - name: Create Release
      uses: ncipollo/release-action@v1.7.3
      with:
        allowUpdates: true
        artifact: midisplit.zip 
        name: latest 
        omitBody: true
        omitBodyDuringUpdate: true
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}



